port:
  clientId: ${PORT_CLIENT_ID}
  clientSecret: ${PORT_CLIENT_SECRET}
  baseUrl: https://api.getport.io/v1
eventListener:
  type: WEBHOOK
integration:
  identifier: spacelift_integration
  type: spacelift
  config:
    api_key: ${SPACELIFT_API_KEY}
    api_secret: ${SPACELIFT_API_SECRET}
    api_endpoint: https://<your-account>.app.spacelift.io/graphql
    filters:
      deployment_status: ["queued", "finished"]
      last_n_days: 7