port:
  clientId: ${PORT_CLIENT_ID}
  clientSecret: ${PORT_CLIENT_SECRET}
eventListener:
  type: WEBHOOK
  shouldResync: true
integration:
  identifier: spacelift
  type: spacelift
  config:
    apiToken: ${SPACELIFT_API_TOKEN}
    apiEndpoint: ${SPACELIFT_API_ENDPOINT}
